/**
 * BIBO.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Mon Oct 15 02:34:40 PDT 2012
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  org.iswc.vocabulary;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  n/a
 *   	comment:   n/a
 */
public class BIBO{

    protected static final String NS = "http://purl.org/ontology/bibo/";

    public static final String getURI(){ return NS; }

	// Class (58)
	 public final static Resource  Film = ResourceFactory.createResource("http://purl.org/ontology/bibo/Film");

	 public final static Resource  Magazine = ResourceFactory.createResource("http://purl.org/ontology/bibo/Magazine");

	 public final static Resource  LegalDecision = ResourceFactory.createResource("http://purl.org/ontology/bibo/LegalDecision");

	 public final static Resource  MultiVolumeBook = ResourceFactory.createResource("http://purl.org/ontology/bibo/MultiVolumeBook");

	 public final static Resource  Letter = ResourceFactory.createResource("http://purl.org/ontology/bibo/Letter");

	 public final static Resource  Event = ResourceFactory.createResource("http://purl.org/ontology/bibo/Event");

	 public final static Resource  BookSection = ResourceFactory.createResource("http://purl.org/ontology/bibo/BookSection");

	 public final static Resource  Document = ResourceFactory.createResource("http://purl.org/ontology/bibo/Document");

	 public final static Resource  ReferenceSource = ResourceFactory.createResource("http://purl.org/ontology/bibo/ReferenceSource");

	 public final static Resource  CollectedDocument = ResourceFactory.createResource("http://purl.org/ontology/bibo/CollectedDocument");

	 public final static Resource  Workshop = ResourceFactory.createResource("http://purl.org/ontology/bibo/Workshop");

	 public final static Resource  Thesis = ResourceFactory.createResource("http://purl.org/ontology/bibo/Thesis");

	 public final static Resource  ThesisDegree = ResourceFactory.createResource("http://purl.org/ontology/bibo/ThesisDegree");

	 public final static Resource  Website = ResourceFactory.createResource("http://purl.org/ontology/bibo/Website");

	 public final static Resource  Manuscript = ResourceFactory.createResource("http://purl.org/ontology/bibo/Manuscript");

	 public final static Resource  Patent = ResourceFactory.createResource("http://purl.org/ontology/bibo/Patent");

	 public final static Resource  AcademicArticle = ResourceFactory.createResource("http://purl.org/ontology/bibo/AcademicArticle");

	 public final static Resource  Brief = ResourceFactory.createResource("http://purl.org/ontology/bibo/Brief");

	 public final static Resource  PersonalCommunication = ResourceFactory.createResource("http://purl.org/ontology/bibo/PersonalCommunication");

	 public final static Resource  EditedBook = ResourceFactory.createResource("http://purl.org/ontology/bibo/EditedBook");

	 public final static Resource  Statute = ResourceFactory.createResource("http://purl.org/ontology/bibo/Statute");

	 public final static Resource  LegalDocument = ResourceFactory.createResource("http://purl.org/ontology/bibo/LegalDocument");

	 public final static Resource  Report = ResourceFactory.createResource("http://purl.org/ontology/bibo/Report");

	 public final static Resource  Performance = ResourceFactory.createResource("http://purl.org/ontology/bibo/Performance");

	 public final static Resource  AudioVisualDocument = ResourceFactory.createResource("http://purl.org/ontology/bibo/AudioVisualDocument");

	 public final static Resource  Hearing = ResourceFactory.createResource("http://purl.org/ontology/bibo/Hearing");

	 public final static Resource  Periodical = ResourceFactory.createResource("http://purl.org/ontology/bibo/Periodical");

	 public final static Resource  Proceedings = ResourceFactory.createResource("http://purl.org/ontology/bibo/Proceedings");

	 public final static Resource  Conference = ResourceFactory.createResource("http://purl.org/ontology/bibo/Conference");

	 public final static Resource  Newspaper = ResourceFactory.createResource("http://purl.org/ontology/bibo/Newspaper");

	 public final static Resource  Journal = ResourceFactory.createResource("http://purl.org/ontology/bibo/Journal");

	 public final static Resource  Quote = ResourceFactory.createResource("http://purl.org/ontology/bibo/Quote");

	 public final static Resource  Series = ResourceFactory.createResource("http://purl.org/ontology/bibo/Series");

	 public final static Resource  Standard = ResourceFactory.createResource("http://purl.org/ontology/bibo/Standard");

	 public final static Resource  Slide = ResourceFactory.createResource("http://purl.org/ontology/bibo/Slide");

	 public final static Resource  Excerpt = ResourceFactory.createResource("http://purl.org/ontology/bibo/Excerpt");

	 public final static Resource  Email = ResourceFactory.createResource("http://purl.org/ontology/bibo/Email");

	 public final static Resource  Image = ResourceFactory.createResource("http://purl.org/ontology/bibo/Image");

	 public final static Resource  Legislation = ResourceFactory.createResource("http://purl.org/ontology/bibo/Legislation");

	 public final static Resource  Interview = ResourceFactory.createResource("http://purl.org/ontology/bibo/Interview");

	 public final static Resource  Chapter = ResourceFactory.createResource("http://purl.org/ontology/bibo/Chapter");

	 public final static Resource  Book = ResourceFactory.createResource("http://purl.org/ontology/bibo/Book");

	 public final static Resource  DocumentPart = ResourceFactory.createResource("http://purl.org/ontology/bibo/DocumentPart");

	 public final static Resource  Manual = ResourceFactory.createResource("http://purl.org/ontology/bibo/Manual");

	 public final static Resource  Map = ResourceFactory.createResource("http://purl.org/ontology/bibo/Map");

	 public final static Resource  Collection = ResourceFactory.createResource("http://purl.org/ontology/bibo/Collection");

	 public final static Resource  CourtReporter = ResourceFactory.createResource("http://purl.org/ontology/bibo/CourtReporter");

	 public final static Resource  LegalCaseDocument = ResourceFactory.createResource("http://purl.org/ontology/bibo/LegalCaseDocument");

	 public final static Resource  DocumentStatus = ResourceFactory.createResource("http://purl.org/ontology/bibo/DocumentStatus");

	 public final static Resource  Slideshow = ResourceFactory.createResource("http://purl.org/ontology/bibo/Slideshow");

	 public final static Resource  Note = ResourceFactory.createResource("http://purl.org/ontology/bibo/Note");

	 public final static Resource  Code = ResourceFactory.createResource("http://purl.org/ontology/bibo/Code");

	 public final static Resource  Article = ResourceFactory.createResource("http://purl.org/ontology/bibo/Article");

	 public final static Resource  AudioDocument = ResourceFactory.createResource("http://purl.org/ontology/bibo/AudioDocument");

	 public final static Resource  Webpage = ResourceFactory.createResource("http://purl.org/ontology/bibo/Webpage");

	 public final static Resource  PersonalCommunicationDocument = ResourceFactory.createResource("http://purl.org/ontology/bibo/PersonalCommunicationDocument");

	 public final static Resource  Issue = ResourceFactory.createResource("http://purl.org/ontology/bibo/Issue");

	 public final static Resource  Bill = ResourceFactory.createResource("http://purl.org/ontology/bibo/Bill");

	// Property (67)
	 public final static Property  lccn = ResourceFactory.createProperty("http://purl.org/ontology/bibo/lccn");

	 public final static Property  court = ResourceFactory.createProperty("http://purl.org/ontology/bibo/court");

	 public final static Property  numVolumes = ResourceFactory.createProperty("http://purl.org/ontology/bibo/numVolumes");

	 public final static Property  volume = ResourceFactory.createProperty("http://purl.org/ontology/bibo/volume");

	 public final static Property  oclcnum = ResourceFactory.createProperty("http://purl.org/ontology/bibo/oclcnum");

	 public final static Property  cites = ResourceFactory.createProperty("http://purl.org/ontology/bibo/cites");

	 public final static Property  issue = ResourceFactory.createProperty("http://purl.org/ontology/bibo/issue");

	 public final static Property  number = ResourceFactory.createProperty("http://purl.org/ontology/bibo/number");

	 public final static Property  section = ResourceFactory.createProperty("http://purl.org/ontology/bibo/section");

	 public final static Property  pmid = ResourceFactory.createProperty("http://purl.org/ontology/bibo/pmid");

	 public final static Property  pageEnd = ResourceFactory.createProperty("http://purl.org/ontology/bibo/pageEnd");

	 public final static Property  interviewer = ResourceFactory.createProperty("http://purl.org/ontology/bibo/interviewer");

	 public final static Property  organizer = ResourceFactory.createProperty("http://purl.org/ontology/bibo/organizer");

	 public final static Property  prefixName = ResourceFactory.createProperty("http://purl.org/ontology/bibo/prefixName");

	 public final static Property  translator = ResourceFactory.createProperty("http://purl.org/ontology/bibo/translator");

	 public final static Property  shortDescription = ResourceFactory.createProperty("http://purl.org/ontology/bibo/shortDescription");

	 public final static Property  interviewee = ResourceFactory.createProperty("http://purl.org/ontology/bibo/interviewee");

	 public final static Property  pages = ResourceFactory.createProperty("http://purl.org/ontology/bibo/pages");

	 public final static Property  doi = ResourceFactory.createProperty("http://purl.org/ontology/bibo/doi");

	 public final static Property  gtin14 = ResourceFactory.createProperty("http://purl.org/ontology/bibo/gtin14");

	 public final static Property  authorList = ResourceFactory.createProperty("http://purl.org/ontology/bibo/authorList");

	 public final static Property  content = ResourceFactory.createProperty("http://purl.org/ontology/bibo/content");

	 public final static Property  degree = ResourceFactory.createProperty("http://purl.org/ontology/bibo/degree");

	 public final static Property  abstract_java = ResourceFactory.createProperty("http://purl.org/ontology/bibo/abstract");

	 public final static Property  editorList = ResourceFactory.createProperty("http://purl.org/ontology/bibo/editorList");

	 public final static Property  shortTitle = ResourceFactory.createProperty("http://purl.org/ontology/bibo/shortTitle");

	 public final static Property  issuer = ResourceFactory.createProperty("http://purl.org/ontology/bibo/issuer");

	 public final static Property  presentedAt = ResourceFactory.createProperty("http://purl.org/ontology/bibo/presentedAt");

	 public final static Property  upc = ResourceFactory.createProperty("http://purl.org/ontology/bibo/upc");

	 public final static Property  translationOf = ResourceFactory.createProperty("http://purl.org/ontology/bibo/translationOf");

	 public final static Property  editor = ResourceFactory.createProperty("http://purl.org/ontology/bibo/editor");

	 public final static Property  argued = ResourceFactory.createProperty("http://purl.org/ontology/bibo/argued");

	 public final static Property  numPages = ResourceFactory.createProperty("http://purl.org/ontology/bibo/numPages");

	 public final static Property  recipient = ResourceFactory.createProperty("http://purl.org/ontology/bibo/recipient");

	 public final static Property  asin = ResourceFactory.createProperty("http://purl.org/ontology/bibo/asin");

	 public final static Property  isbn13 = ResourceFactory.createProperty("http://purl.org/ontology/bibo/isbn13");

	 public final static Property  isbn10 = ResourceFactory.createProperty("http://purl.org/ontology/bibo/isbn10");

	 public final static Property  eanucc13 = ResourceFactory.createProperty("http://purl.org/ontology/bibo/eanucc13");

	 public final static Property  identifier = ResourceFactory.createProperty("http://purl.org/ontology/bibo/identifier");

	 public final static Property  reproducedIn = ResourceFactory.createProperty("http://purl.org/ontology/bibo/reproducedIn");

	 public final static Property  affirmedBy = ResourceFactory.createProperty("http://purl.org/ontology/bibo/affirmedBy");

	 public final static Property  citedBy = ResourceFactory.createProperty("http://purl.org/ontology/bibo/citedBy");

	 public final static Property  presents = ResourceFactory.createProperty("http://purl.org/ontology/bibo/presents");

	 public final static Property  sici = ResourceFactory.createProperty("http://purl.org/ontology/bibo/sici");

	 public final static Property  contributorList = ResourceFactory.createProperty("http://purl.org/ontology/bibo/contributorList");

	 public final static Property  subsequentLegalDecision = ResourceFactory.createProperty("http://purl.org/ontology/bibo/subsequentLegalDecision");

	 public final static Property  reviewOf = ResourceFactory.createProperty("http://purl.org/ontology/bibo/reviewOf");

	 public final static Property  performer = ResourceFactory.createProperty("http://purl.org/ontology/bibo/performer");

	 public final static Property  isbn = ResourceFactory.createProperty("http://purl.org/ontology/bibo/isbn");

	 public final static Property  transcriptOf = ResourceFactory.createProperty("http://purl.org/ontology/bibo/transcriptOf");

	 public final static Property  handle = ResourceFactory.createProperty("http://purl.org/ontology/bibo/handle");

	 public final static Property  distributor = ResourceFactory.createProperty("http://purl.org/ontology/bibo/distributor");

	 public final static Property  locator = ResourceFactory.createProperty("http://purl.org/ontology/bibo/locator");

	 public final static Property  producer = ResourceFactory.createProperty("http://purl.org/ontology/bibo/producer");

	 public final static Property  coden = ResourceFactory.createProperty("http://purl.org/ontology/bibo/coden");

	 public final static Property  uri = ResourceFactory.createProperty("http://purl.org/ontology/bibo/uri");

	 public final static Property  status = ResourceFactory.createProperty("http://purl.org/ontology/bibo/status");

	 public final static Property  eissn = ResourceFactory.createProperty("http://purl.org/ontology/bibo/eissn");

	 public final static Property  annotates = ResourceFactory.createProperty("http://purl.org/ontology/bibo/annotates");

	 public final static Property  director = ResourceFactory.createProperty("http://purl.org/ontology/bibo/director");

	 public final static Property  suffixName = ResourceFactory.createProperty("http://purl.org/ontology/bibo/suffixName");

	 public final static Property  owner = ResourceFactory.createProperty("http://purl.org/ontology/bibo/owner");

	 public final static Property  issn = ResourceFactory.createProperty("http://purl.org/ontology/bibo/issn");

	 public final static Property  edition = ResourceFactory.createProperty("http://purl.org/ontology/bibo/edition");

	 public final static Property  chapter = ResourceFactory.createProperty("http://purl.org/ontology/bibo/chapter");

	 public final static Property  pageStart = ResourceFactory.createProperty("http://purl.org/ontology/bibo/pageStart");

	 public final static Property  reversedBy = ResourceFactory.createProperty("http://purl.org/ontology/bibo/reversedBy");

	// Instance (14)
	 public final static Resource  bdarcus = ResourceFactory.createResource("http://purl.org/ontology/bibo/bdarcus");

	 public final static Resource  status_legal = ResourceFactory.createResource("http://purl.org/ontology/bibo/status/legal");

	 public final static Resource  status_nonPeerReviewed = ResourceFactory.createResource("http://purl.org/ontology/bibo/status/nonPeerReviewed");

	 public final static Resource  status_draft = ResourceFactory.createResource("http://purl.org/ontology/bibo/status/draft");

	 public final static Resource  fgiasson = ResourceFactory.createResource("http://purl.org/ontology/bibo/fgiasson");

	 public final static Resource  status_published = ResourceFactory.createResource("http://purl.org/ontology/bibo/status/published");

	 public final static Resource  status_rejected = ResourceFactory.createResource("http://purl.org/ontology/bibo/status/rejected");

	 public final static Resource  degrees_phd = ResourceFactory.createResource("http://purl.org/ontology/bibo/degrees/phd");

	 public final static Resource  status_accepted = ResourceFactory.createResource("http://purl.org/ontology/bibo/status/accepted");

	 public final static Resource  status_unpublished = ResourceFactory.createResource("http://purl.org/ontology/bibo/status/unpublished");

	 public final static Resource  degrees_ma = ResourceFactory.createResource("http://purl.org/ontology/bibo/degrees/ma");

	 public final static Resource  status_peerReviewed = ResourceFactory.createResource("http://purl.org/ontology/bibo/status/peerReviewed");

	 public final static Resource  status_forthcoming = ResourceFactory.createResource("http://purl.org/ontology/bibo/status/forthcoming");

	 public final static Resource  degrees_ms = ResourceFactory.createResource("http://purl.org/ontology/bibo/degrees/ms");



}


 
