/**
 * DGTWC.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Sun Dec 20 18:30:10 EST 2009
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  org.iswc.vocabulary;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  dgtwc ontology@en
 *   	comment:   The ontology for RDF data published at http://data-gov.tw.rpi.edu. @en
 */
public class DGTWC{

    protected static final String NS = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#";

    public static final String getURI(){ return NS; }

	// Class (3)
	 public final static String Datafile_lname = "Datafile";
	 public final static String Datafile_qname = "dgtwc:Datafile";
	 public final static String Datafile_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#Datafile";
	 public final static Resource  Datafile = ResourceFactory.createResource(Datafile_uri);

	 public final static String DataEntry_lname = "DataEntry";
	 public final static String DataEntry_qname = "dgtwc:DataEntry";
	 public final static String DataEntry_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#DataEntry";
	 public final static Resource  DataEntry = ResourceFactory.createResource(DataEntry_uri);

	 public final static String Dataset_lname = "Dataset";
	 public final static String Dataset_qname = "dgtwc:Dataset";
	 public final static String Dataset_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#Dataset";
	 public final static Resource  Dataset = ResourceFactory.createResource(Dataset_uri);

	// Property (16)
	 public final static String complete_data_lname = "complete_data";
	 public final static String complete_data_qname = "dgtwc:complete_data";
	 public final static String complete_data_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#complete_data";
	 public final static Property  complete_data = ResourceFactory.createProperty(complete_data_uri);

	 public final static String more_data_lname = "more_data";
	 public final static String more_data_qname = "dgtwc:more_data";
	 public final static String more_data_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#more_data";
	 public final static Property  more_data = ResourceFactory.createProperty(more_data_uri);

	 public final static String number_of_datasets_lname = "number_of_datasets";
	 public final static String number_of_datasets_qname = "dgtwc:number_of_datasets";
	 public final static String number_of_datasets_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#number_of_datasets";
	 public final static Property  number_of_datasets = ResourceFactory.createProperty(number_of_datasets_uri);

	 public final static String number_of_bytes_lname = "number_of_bytes";
	 public final static String number_of_bytes_qname = "dgtwc:number_of_bytes";
	 public final static String number_of_bytes_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#number_of_bytes";
	 public final static Property  number_of_bytes = ResourceFactory.createProperty(number_of_bytes_uri);

	 public final static String uses_property_lname = "uses_property";
	 public final static String uses_property_qname = "dgtwc:uses_property";
	 public final static String uses_property_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#uses_property";
	 public final static Property  uses_property = ResourceFactory.createProperty(uses_property_uri);

	 public final static String number_of_properties_lname = "number_of_properties";
	 public final static String number_of_properties_qname = "dgtwc:number_of_properties";
	 public final static String number_of_properties_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#number_of_properties";
	 public final static Property  number_of_properties = ResourceFactory.createProperty(number_of_properties_uri);

	 public final static String number_of_entries_lname = "number_of_entries";
	 public final static String number_of_entries_qname = "dgtwc:number_of_entries";
	 public final static String number_of_entries_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#number_of_entries";
	 public final static Property  number_of_entries = ResourceFactory.createProperty(number_of_entries_uri);

	 public final static String link_data_lname = "link_data";
	 public final static String link_data_qname = "dgtwc:link_data";
	 public final static String link_data_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#link_data";
	 public final static Property  link_data = ResourceFactory.createProperty(link_data_uri);

	 public final static String number_of_triples_lname = "number_of_triples";
	 public final static String number_of_triples_qname = "dgtwc:number_of_triples";
	 public final static String number_of_triples_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#number_of_triples";
	 public final static Property  number_of_triples = ResourceFactory.createProperty(number_of_triples_uri);

	 public final static String partial_data_lname = "partial_data";
	 public final static String partial_data_qname = "dgtwc:partial_data";
	 public final static String partial_data_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#partial_data";
	 public final static Property  partial_data = ResourceFactory.createProperty(partial_data_uri);

	 public final static String isPartOf_lname = "isPartOf";
	 public final static String isPartOf_qname = "dgtwc:isPartOf";
	 public final static String isPartOf_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#isPartOf";
	 public final static Property  isPartOf = ResourceFactory.createProperty(isPartOf_uri);

	 public final static String abbreviation_lname = "abbreviation";
	 public final static String abbreviation_qname = "dgtwc:abbreviation";
	 public final static String abbreviation_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#abbreviation";
	 public final static Property  abbreviation = ResourceFactory.createProperty(abbreviation_uri);

	 public final static String code_lname = "code";
	 public final static String code_qname = "dgtwc:code";
	 public final static String code_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#code";
	 public final static Property  code = ResourceFactory.createProperty(code_uri);

	 public final static String imports_lname = "imports";
	 public final static String imports_qname = "dgtwc:imports";
	 public final static String imports_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#imports";
	 public final static Property  imports = ResourceFactory.createProperty(imports_uri);

	 public final static String hasPart_lname = "hasPart";
	 public final static String hasPart_qname = "dgtwc:hasPart";
	 public final static String hasPart_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#hasPart";
	 public final static Property  hasPart = ResourceFactory.createProperty(hasPart_uri);

	 public final static String sparql_endpoint_lname = "sparql_endpoint";
	 public final static String sparql_endpoint_qname = "dgtwc:sparql_endpoint";
	 public final static String sparql_endpoint_uri = "http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#sparql_endpoint";
	 public final static Property  sparql_endpoint = ResourceFactory.createProperty(sparql_endpoint_uri);

	// Instance (0)


}


 
