/**
 * SWRC.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Mon Oct 15 02:34:38 PDT 2012
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  org.iswc.vocabulary;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  n/a
 *   	comment:   n/a
 */
public class SWRC{

    protected static final String NS = "http://swrc.ontoware.org/ontology#";

    public static final String getURI(){ return NS; }

	// Class (54)
	 public final static Resource  PhDThesis = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#PhDThesis");

	 public final static Resource  Booklet = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Booklet");

	 public final static Resource  Topic = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Topic");

	 public final static Resource  FacultyMember = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#FacultyMember");

	 public final static Resource  Department = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Department");

	 public final static Resource  SoftwareProject = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#SoftwareProject");

	 public final static Resource  ResearchTopic = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#ResearchTopic");

	 public final static Resource  Event = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Event");

	 public final static Resource  MasterThesis = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#MasterThesis");

	 public final static Resource  Institute = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Institute");

	 public final static Resource  InCollection = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#InCollection");

	 public final static Resource  Misc = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Misc");

	 public final static Resource  Workshop = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Workshop");

	 public final static Resource  Report = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Report");

	 public final static Resource  AssistantProfessor = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#AssistantProfessor");

	 public final static Resource  InBook = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#InBook");

	 public final static Resource  Lecture = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Lecture");

	 public final static Resource  AssociateProfessor = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#AssociateProfessor");

	 public final static Resource  Project = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Project");

	 public final static Resource  University = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#University");

	 public final static Resource  Thesis = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Thesis");

	 public final static Resource  PhDStudent = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#PhDStudent");

	 public final static Resource  Conference = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Conference");

	 public final static Resource  Book = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Book");

	 public final static Resource  FullProfessor = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#FullProfessor");

	 public final static Resource  Graduate = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Graduate");

	 public final static Resource  Student = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Student");

	 public final static Resource  InProceedings = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#InProceedings");

	 public final static Resource  Unpublished = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Unpublished");

	 public final static Resource  DevelopmentProject = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#DevelopmentProject");

	 public final static Resource  Person = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Person");

	 public final static Resource  Proceedings = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Proceedings");

	 public final static Resource  Lecturer = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Lecturer");

	 public final static Resource  Article = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Article");

	 public final static Resource  ResearchProject = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#ResearchProject");

	 public final static Resource  Organization = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Organization");

	 public final static Resource  Association = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Association");

	 public final static Resource  Product = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Product");

	 public final static Resource  ProjectReport = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#ProjectReport");

	 public final static Resource  Meeting = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Meeting");

	 public final static Resource  Employee = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Employee");

	 public final static Resource  TechnicalReport = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#TechnicalReport");

	 public final static Resource  Undergraduate = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Undergraduate");

	 public final static Resource  Publication = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Publication");

	 public final static Resource  TechnicalStaff = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#TechnicalStaff");

	 public final static Resource  Enterprise = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Enterprise");

	 public final static Resource  SoftwareComponent = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#SoftwareComponent");

	 public final static Resource  AdministrativeStaff = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#AdministrativeStaff");

	 public final static Resource  Manual = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Manual");

	 public final static Resource  AcademicStaff = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#AcademicStaff");

	 public final static Resource  Exhibition = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Exhibition");

	 public final static Resource  Manager = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#Manager");

	 public final static Resource  ProjectMeeting = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#ProjectMeeting");

	 public final static Resource  ResearchGroup = ResourceFactory.createResource("http://swrc.ontoware.org/ontology#ResearchGroup");

	// Property (74)
	 public final static Property  fax = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#fax");

	 public final static Property  headOf = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#headOf");

	 public final static Property  journal = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#journal");

	 public final static Property  RootRelation = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#RootRelation");

	 public final static Property  editor = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#editor");

	 public final static Property  developedBy = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#developedBy");

	 public final static Property  develops = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#develops");

	 public final static Property  title = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#title");

	 public final static Property  phone = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#phone");

	 public final static Property  hasPrice = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#hasPrice");

	 public final static Property  technicalReport = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#technicalReport");

	 public final static Property  abstract_java = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#abstract");

	 public final static Property  isAbout = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#isAbout");

	 public final static Property  organization = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#organization");

	 public final static Property  edition = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#edition");

	 public final static Property  chapter = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#chapter");

	 public final static Property  member = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#member");

	 public final static Property  employs = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#employs");

	 public final static Property  supervises = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#supervises");

	 public final static Property  hasParts = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#hasParts");

	 public final static Property  financedBy = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#financedBy");

	 public final static Property  isWorkedOnBy = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#isWorkedOnBy");

	 public final static Property  date = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#date");

	 public final static Property  carriesOut = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#carriesOut");

	 public final static Property  projectInfo = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#projectInfo");

	 public final static Property  describesProject = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#describesProject");

	 public final static Property  worksAtProject = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#worksAtProject");

	 public final static Property  address = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#address");

	 public final static Property  note = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#note");

	 public final static Property  carriedOutBy = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#carriedOutBy");

	 public final static Property  email = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#email");

	 public final static Property  howpublished = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#howpublished");

	 public final static Property  supervisor = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#supervisor");

	 public final static Property  cooperateWith = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#cooperateWith");

	 public final static Property  head = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#head");

	 public final static Property  isbn = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#isbn");

	 public final static Property  Root = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#Root");

	 public final static Property  number = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#number");

	 public final static Property  pages = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#pages");

	 public final static Property  finances = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#finances");

	 public final static Property  location = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#location");

	 public final static Property  cite = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#cite");

	 public final static Property  product = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#product");

	 public final static Property  price = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#price");

	 public final static Property  school = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#school");

	 public final static Property  photo = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#photo");

	 public final static Property  student = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#student");

	 public final static Property  dealtWithIn = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#dealtWithIn");

	 public final static Property  citedBy = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#citedBy");

	 public final static Property  organizerOrChairOf = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#organizerOrChairOf");

	 public final static Property  series = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#series");

	 public final static Property  name = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#name");

	 public final static Property  headOfGroup = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#headOfGroup");

	 public final static Property  eventTitle = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#eventTitle");

	 public final static Property  volume = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#volume");

	 public final static Property  booktitle = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#booktitle");

	 public final static Property  memberOfPC = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#memberOfPC");

	 public final static Property  type = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#type");

	 public final static Property  participant = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#participant");

	 public final static Property  hasPartEvent = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#hasPartEvent");

	 public final static Property  studiesAt = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#studiesAt");

	 public final static Property  author = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#author");

	 public final static Property  institution = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#institution");

	 public final static Property  keywords = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#keywords");

	 public final static Property  source = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#source");

	 public final static Property  atEvent = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#atEvent");

	 public final static Property  affiliation = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#affiliation");

	 public final static Property  homepage = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#homepage");

	 public final static Property  month = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#month");

	 public final static Property  givenBy = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#givenBy");

	 public final static Property  publisher = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#publisher");

	 public final static Property  publishes = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#publishes");

	 public final static Property  year = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#year");

	 public final static Property  publication = ResourceFactory.createProperty("http://swrc.ontoware.org/ontology#publication");

	// Instance (0)


}


 
